### web
server:
  port: 8080
  context-path: /code-generator

### freemarker
spring:
  freemarker:
    request-context-attribute: request
    cache: false
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    content-type: text/html

### resource
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

### mysql datasource
  datasource:
    name: gysDataSource
    url: jdbc:mysql://localhost:3306
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15

### mybatis
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.liaojs.codegenerator.model
